# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CosmoGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CosmoWindow(object):
    def setupUi(self, CosmoWindow):
        CosmoWindow.setObjectName("CosmoWindow")
        CosmoWindow.resize(625, 744)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CosmoWindow.sizePolicy().hasHeightForWidth())
        CosmoWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(CosmoWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_Main = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_Main.setGeometry(QtCore.QRect(0, 0, 621, 691))
        self.tab_Main.setStatusTip("")
        self.tab_Main.setObjectName("tab_Main")
        self.Tab_Control = QtWidgets.QWidget()
        self.Tab_Control.setWhatsThis("")
        self.Tab_Control.setObjectName("Tab_Control")
        self.label_Picture = QtWidgets.QLabel(self.Tab_Control)
        self.label_Picture.setGeometry(QtCore.QRect(131, 110, 280, 251))
        self.label_Picture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Picture.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Picture.setText("")
        self.label_Picture.setPixmap(QtGui.QPixmap("images/picoCosmo_iconic.jpg"))
        self.label_Picture.setObjectName("label_Picture")
        self.label_caption = QtWidgets.QLabel(self.Tab_Control)
        self.label_caption.setGeometry(QtCore.QRect(90, 70, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_caption.setFont(font)
        self.label_caption.setObjectName("label_caption")
        self.label_DAQconfig = QtWidgets.QLabel(self.Tab_Control)
        self.label_DAQconfig.setGeometry(QtCore.QRect(50, 419, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Latin Modern Sans")
        font.setPointSize(11)
        self.label_DAQconfig.setFont(font)
        self.label_DAQconfig.setTextFormat(QtCore.Qt.PlainText)
        self.label_DAQconfig.setObjectName("label_DAQconfig")
        self.lE_DAQConfFile = QtWidgets.QLineEdit(self.Tab_Control)
        self.lE_DAQConfFile.setGeometry(QtCore.QRect(160, 420, 371, 32))
        self.lE_DAQConfFile.setText("")
        self.lE_DAQConfFile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lE_DAQConfFile.setReadOnly(True)
        self.lE_DAQConfFile.setObjectName("lE_DAQConfFile")
        self.pB_FileSelect = QtWidgets.QPushButton(self.Tab_Control)
        self.pB_FileSelect.setGeometry(QtCore.QRect(540, 420, 31, 34))
        self.pB_FileSelect.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/open-folder.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_FileSelect.setIcon(icon)
        self.pB_FileSelect.setObjectName("pB_FileSelect")
        self.pB_abort = QtWidgets.QPushButton(self.Tab_Control)
        self.pB_abort.setGeometry(QtCore.QRect(505, 0, 41, 41))
        self.pB_abort.setAccessibleDescription("")
        self.pB_abort.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/application-exit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_abort.setIcon(icon1)
        self.pB_abort.setIconSize(QtCore.QSize(20, 20))
        self.pB_abort.setAutoDefault(False)
        self.pB_abort.setObjectName("pB_abort")
        self.lE_WorkDir = QtWidgets.QLineEdit(self.Tab_Control)
        self.lE_WorkDir.setGeometry(QtCore.QRect(160, 500, 371, 32))
        self.lE_WorkDir.setReadOnly(True)
        self.lE_WorkDir.setObjectName("lE_WorkDir")
        self.label_WorkDir = QtWidgets.QLabel(self.Tab_Control)
        self.label_WorkDir.setGeometry(QtCore.QRect(60, 506, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Latin Modern Sans")
        font.setPointSize(11)
        self.label_WorkDir.setFont(font)
        self.label_WorkDir.setObjectName("label_WorkDir")
        self.pB_WDselect = QtWidgets.QPushButton(self.Tab_Control)
        self.pB_WDselect.setGeometry(QtCore.QRect(540, 500, 31, 34))
        self.pB_WDselect.setText("")
        self.pB_WDselect.setIcon(icon)
        self.pB_WDselect.setObjectName("pB_WDselect")
        self.tab_Main.addTab(self.Tab_Control, "")
        self.Tab_Config = QtWidgets.QWidget()
        self.Tab_Config.setObjectName("Tab_Config")
        self.tabWidget = QtWidgets.QTabWidget(self.Tab_Config)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(811, 0))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.OsciConfig = QtWidgets.QWidget()
        self.OsciConfig.setObjectName("OsciConfig")
        self.pTE_OsciConfig = QtWidgets.QPlainTextEdit(self.OsciConfig)
        self.pTE_OsciConfig.setGeometry(QtCore.QRect(0, 10, 601, 381))
        self.pTE_OsciConfig.setReadOnly(True)
        self.pTE_OsciConfig.setObjectName("pTE_OsciConfig")
        self.pB_loadPSconf = QtWidgets.QPushButton(self.OsciConfig)
        self.pB_loadPSconf.setGeometry(QtCore.QRect(390, 390, 151, 31))
        self.pB_loadPSconf.setIcon(icon)
        self.pB_loadPSconf.setObjectName("pB_loadPSconf")
        self.tabWidget.addTab(self.OsciConfig, "")
        self.PulseFilterConfig = QtWidgets.QWidget()
        self.PulseFilterConfig.setObjectName("PulseFilterConfig")
        self.pTE_PFconfig = QtWidgets.QPlainTextEdit(self.PulseFilterConfig)
        self.pTE_PFconfig.setGeometry(QtCore.QRect(0, 10, 601, 381))
        self.pTE_PFconfig.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pTE_PFconfig.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pTE_PFconfig.setReadOnly(True)
        self.pTE_PFconfig.setObjectName("pTE_PFconfig")
        self.pB_loadPFconf = QtWidgets.QPushButton(self.PulseFilterConfig)
        self.pB_loadPFconf.setGeometry(QtCore.QRect(390, 390, 151, 30))
        self.pB_loadPFconf.setIcon(icon)
        self.pB_loadPFconf.setObjectName("pB_loadPFconf")
        self.tabWidget.addTab(self.PulseFilterConfig, "")
        self.BMconfig = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BMconfig.sizePolicy().hasHeightForWidth())
        self.BMconfig.setSizePolicy(sizePolicy)
        self.BMconfig.setObjectName("BMconfig")
        self.pTE_BMconfig = QtWidgets.QPlainTextEdit(self.BMconfig)
        self.pTE_BMconfig.setGeometry(QtCore.QRect(0, 10, 601, 381))
        self.pTE_BMconfig.setReadOnly(True)
        self.pTE_BMconfig.setObjectName("pTE_BMconfig")
        self.pB_loadBMconf = QtWidgets.QPushButton(self.BMconfig)
        self.pB_loadBMconf.setGeometry(QtCore.QRect(390, 390, 151, 31))
        self.pB_loadBMconf.setIcon(icon)
        self.pB_loadBMconf.setObjectName("pB_loadBMconf")
        self.tabWidget.addTab(self.BMconfig, "")
        self.rB_EditMode = QtWidgets.QRadioButton(self.Tab_Config)
        self.rB_EditMode.setGeometry(QtCore.QRect(410, 10, 111, 30))
        self.rB_EditMode.setObjectName("rB_EditMode")
        self.pB_SaveConfig = QtWidgets.QPushButton(self.Tab_Config)
        self.pB_SaveConfig.setGeometry(QtCore.QRect(200, 620, 131, 30))
        self.pB_SaveConfig.setObjectName("pB_SaveConfig")
        self.pTE_DAQConfig = QtWidgets.QPlainTextEdit(self.Tab_Config)
        self.pTE_DAQConfig.setGeometry(QtCore.QRect(10, 493, 611, 120))
        self.pTE_DAQConfig.setReadOnly(True)
        self.pTE_DAQConfig.setObjectName("pTE_DAQConfig")
        self.pB_ReloadConfig = QtWidgets.QPushButton(self.Tab_Config)
        self.pB_ReloadConfig.setEnabled(False)
        self.pB_ReloadConfig.setGeometry(QtCore.QRect(419, 609, 111, 31))
        self.pB_ReloadConfig.setObjectName("pB_ReloadConfig")
        self.tab_Main.addTab(self.Tab_Config, "")
        self.Tab_Help = QtWidgets.QWidget()
        self.Tab_Help.setObjectName("Tab_Help")
        self.TE_Help = QtWidgets.QTextEdit(self.Tab_Help)
        self.TE_Help.setGeometry(QtCore.QRect(11, 36, 601, 611))
        self.TE_Help.setUndoRedoEnabled(False)
        self.TE_Help.setReadOnly(True)
        self.TE_Help.setPlaceholderText("")
        self.TE_Help.setObjectName("TE_Help")
        self.pB_Help = QtWidgets.QPushButton(self.Tab_Help)
        self.pB_Help.setGeometry(QtCore.QRect(10, 3, 88, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/flagUK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Help.setIcon(icon2)
        self.pB_Help.setObjectName("pB_Help")
        self.pB_Hilfe = QtWidgets.QPushButton(self.Tab_Help)
        self.pB_Hilfe.setGeometry(QtCore.QRect(112, 3, 88, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/flagDE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_Hilfe.setIcon(icon3)
        self.pB_Hilfe.setObjectName("pB_Hilfe")
        self.tab_Main.addTab(self.Tab_Help, "")
        self.pB_StartRun = QtWidgets.QPushButton(self.centralwidget)
        self.pB_StartRun.setGeometry(QtCore.QRect(508, 701, 101, 40))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/start.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_StartRun.setIcon(icon4)
        self.pB_StartRun.setIconSize(QtCore.QSize(24, 24))
        self.pB_StartRun.setObjectName("pB_StartRun")
        self.lE_RunTag = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_RunTag.setGeometry(QtCore.QRect(240, 700, 171, 31))
        self.lE_RunTag.setObjectName("lE_RunTag")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 697, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Latin Modern Sans")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        CosmoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CosmoWindow)
        self.tab_Main.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CosmoWindow)

    def retranslateUi(self, CosmoWindow):
        _translate = QtCore.QCoreApplication.translate
        CosmoWindow.setWindowTitle(_translate("CosmoWindow", "CosmoGui"))
        self.tab_Main.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Output  / Configuration / Help</p></body></html>"))
        self.Tab_Control.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Control Panel</p></body></html>"))
        self.label_caption.setText(_translate("CosmoWindow", "Kamiokanne & CosMO Detector with PicoScope"))
        self.label_DAQconfig.setText(_translate("CosmoWindow", "DAQ config:"))
        self.lE_DAQConfFile.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>DAQ configuration file (type .daq)</p></body></html>"))
        self.pB_FileSelect.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>selecd daq configuration file</p></body></html>"))
        self.pB_abort.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Exit CosmoGui</p></body></html>"))
        self.label_WorkDir.setText(_translate("CosmoWindow", "Work Dir:"))
        self.pB_WDselect.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>select working directory (where ouput is stored)</p></body></html>"))
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.Tab_Control), _translate("CosmoWindow", "Control"))
        self.Tab_Config.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Config Panel</p></body></html>"))
        self.tabWidget.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Configuration Files</p></body></html>"))
        self.pTE_OsciConfig.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Configuration File for Oscilloscope</p></body></html>"))
        self.pB_loadPSconf.setToolTip(_translate("CosmoWindow", "Load PicoScope configuration"))
        self.pB_loadPSconf.setText(_translate("CosmoWindow", "load PS config"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OsciConfig), _translate("CosmoWindow", "Oscilloscope"))
        self.pTE_PFconfig.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Configuration File for Pulse Filter and Analysis</p></body></html>"))
        self.pB_loadPFconf.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Load PulseFilter configuration from File</p></body></html>"))
        self.pB_loadPFconf.setText(_translate("CosmoWindow", "load PF config"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PulseFilterConfig), _translate("CosmoWindow", "PulseFilter"))
        self.pTE_BMconfig.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Configuration File for Buffer Manager</p></body></html>"))
        self.pB_loadBMconf.setToolTip(_translate("CosmoWindow", "Load Buffer Manager configuration"))
        self.pB_loadBMconf.setText(_translate("CosmoWindow", "load BM config"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BMconfig), _translate("CosmoWindow", "BufferManager"))
        self.rB_EditMode.setText(_translate("CosmoWindow", "Edit Mode"))
        self.pB_SaveConfig.setToolTip(_translate("CosmoWindow", "Save as default configuration"))
        self.pB_SaveConfig.setText(_translate("CosmoWindow", "Save all configs"))
        self.pTE_DAQConfig.setToolTip(_translate("CosmoWindow", "DAQ configuration: list of configuration filenames"))
        self.pB_ReloadConfig.setText(_translate("CosmoWindow", "Reload configs"))
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.Tab_Config), _translate("CosmoWindow", "Configuration"))
        self.Tab_Help.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Info &amp; Help</p></body></html>"))
        self.pB_Help.setText(_translate("CosmoWindow", "English"))
        self.pB_Hilfe.setText(_translate("CosmoWindow", "Deutsch"))
        self.tab_Main.setTabText(self.tab_Main.indexOf(self.Tab_Help), _translate("CosmoWindow", "Help / Hilfe"))
        self.pB_StartRun.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Start Runinng Oscilloscope, Buffer Manager and Pulse Filter</p></body></html>"))
        self.pB_StartRun.setText(_translate("CosmoWindow", "  StartRun"))
        self.lE_RunTag.setToolTip(_translate("CosmoWindow", "<html><head/><body><p>Name for the run</p></body></html>"))
        self.lE_RunTag.setText(_translate("CosmoWindow", "CosmoRun"))
        self.label.setText(_translate("CosmoWindow", "Run Tag:"))
