# Configuration file for PulseFilter (rate measurement)

# output files 
logFile: pFilt   # store all pulses, Null to disable
# logFile2: dpFilt  # store double-pulse parameters

#rawFile:  dpRaw    # store raw wave-forms
#pictFile: dpFigs   # save pictures of double pulses

# pulse parameters
#         ____
#        /    \  
#     _ /_ _ _ \_ _
#                 
#      r   on  f 
#                 

# shape for all pulses
pulseShape:
 - pheight: -0.030
   taur   : 20.E-9
   tauon  : 12.E-9 
   tauf   : 128.E-9 

NminCoincidence: 2  # set number of Coincidences 


modules: [RMeter, Display]

doublePulse: false # switch to control double-pulse search



