# Configuration file for PulseFilter (efficiency measurement)

# three Panels A, B and C on top of each other
#  efficiency of middle one , B, is measured

# output files 
logFile: pFilt   # store all pulses, Null to disable
# logFile2: dpFilt  # store double-pulse parameters

#rawFile1:  pRaw    # store raw wave-forms
#Nraw1: 100         # number of raw wave-forms to store
#rawFile:  dpRaw    # store raw wave-forms
#pictFile: dpFigs   # save pictures of double pulses

# pulse parameters
#         ____
#        /    \  
#     _ /_ _ _ \_ _
#                 
#       r  on  f 
                 
# shape for all pulses
pulseShape:   # for new (Series III) CosMO panels
 - pheight: -0.010
   taur   : 20.E-9
   tauon  : 200.E-9 
   tauf   : 1.E-6 

# for old panels:
#   tauon  : 100.E-9 
#   tauf   : 150.E-9 


# for efficincy: require signals in A and C (trigger on A or C)
acceptPattern:     
 - [1, 1, 1]  # valid pulse A and B and C OR 
 - [1, 0, 1]  # valid pulse A and not B and C

# for noise level: require signals only in trigger panel B 
#NminCoincidence: 1  # set number of Coincidences 
# alternatively fir noise level: apply veto already at selection level
##acceptPattern:     
## - [0, 1, 0]  # valid pulse only in B, but not A and not C

modules: [RMeter, Display, Hists]

histograms:
  # min max Nbins ymax    title              lin/log
 - [0., 0.2, 50, 20., "noise Trg. Pulse (V)", 0]
 - [0., 0.5, 50, 15., "valid Trg. Pulse (V)", 0]
 - [0., 15.,  45, 7.5, "Tau (µs)", 1]
 - [0., 0.5, 50, 15., "Pulse Height (V)", 0]

doublePulse: false # switch to control double-pulse search
