# demo configuration file for PulseFilter
#    documents all options

## output files 
logFile: pFilt   # store all pulses, Null to disable
logFile2: dpFilt  # store double-pulse parameters

rawFile:  dpRaw    # store raw wave-forms
pictFile: dpFigs   # save pictures of double pulses

## pulse parameters
#              ____
#             /    \  
#    ____, _ /_ _ _ \_ _ _ _ _ _  
#                    \_______/   
#      d     r  on f f2 off r2
#                 

pulseShape:
# channel A:
 - pheight: -0.040
   taur   : 20.E-9
   tauon  : 12.E-9 
   tauf   : 128.E-9
   OffsetSubtraction: true # opt., subtract dc offset for uni-polar pulse (default)

# channel B: 
 - pheight: -0.040
   taur   : 20.E-9
   tauon  : 12.E-9 
   tauf   : 128.E-9 
   delay  : 0.000       # optional: delay w.r.t. trigger channel
   OffsetSubtraction: true # subtract dc offset for uni-polar pulse (default)

trgPulseShape:
# trigger pulse
 - pheight: -0.040
   taur   : 20.E-9
   tauon  : 12.E-9 
   tauf   : 128.E-9 

# precision of timing between channels
timingPrecision: 2 # in units of sampling interval, default is 2

## criteria to accept event (optional)
NminCoincidence: 1 # min nbr of coincidences to accept event
#   # pulses required near trigger pulse (overwrites NminCoincience)
#acceptPattern:     
# - [1, 1]  # chanA and ChanB
# - [0, 1]  # not ChanA and ChanB
# - [1, 0]  # ChanA and not ChanB

## display modules to start and options
modules: [RMeter, Display, Hists]

RMeterInterval:  2.5  # update interval in sec.
RMeterRate:  12.  # max rate in Hz
RMeterTitle: 'rate history (s)'

histograms:
  # min max Nbins ymax    title              lin/log
 - [0., 0.4, 50, 20., "noise Trg. Pulse (V)", 0]
 - [0., 0.8, 50, 15., "valid Trg. Pulse (V)", 0]
 - [0., 15.,  45, 7.5, "Tau (µs)", 1]
 - [0., 0.8, 50, 15., "Pulse Height (V)", 0]

## analysis options
doublePulse: true  # switch to control double-pulse search
