# Configuration file for PulseFilter (rate measurement)
#    for gamma detector GDK101

# output files 
logFile: pFilt   # store all pulses, Null to disable
logFile2: null   # store double-pulse parameters, null to disable

#rawFile:  dpRaw    # store raw wave-forms
#pictFile: dpFigs   # save pictures of double pulses

# pulse parameters
#         ____
#        /    \  
#     _ /_ _ _ \_ _
#                 
#      r   on  f 
#                 

# shape for all pulses
pulseShape:
 - pheight: 0.100
   taur   : 20.E-6
   tauon  : 1.E-6 
   tauf   : 100.E-6 

NminCoincidence: 1  # set number of Coincidences 

modules: [RMeter, Display]
RMeterInterval:  60.  # update interval in sec.
RMeterRate:  0.1  # max rate in Hz
RMeterTitle: 'gamma rate history (s)'

doublePulse: false # switch to control double-pulse search



