# Configuration file for PulseFilter (rate measurement)
#    for gamma detector GDK101

# output files 
logFile: pFilt_gamma   # store all pulses, Null to disable
logFile2: null   # store double-pulse parameters, null to disable

#rawFile:  dpRaw    # store raw wave-forms
#pictFile: dpFigs   # save pictures of double pulses

# pulse parameters
#         ____
#        /    \  
#     _ /_ _ _ \_ _ _ _ _ _  
#               \_______/   
#      r  on  f f2 off r2
#                 

# shape for all pulses
pulseShape:            # bipolar pulse
 - pheight: 0.100
   taur   :  55.E-6
   tauon  :  15.E-6 
   tauf   : 100.E-6 
   mode   : 1
   tauf2  : 100.E-6 
   tauoff :  50.E-6
   taur2  : 300.E-6

NminCoincidence: 1  # set number of Coincidences 

modules: [RMeter, Display, Hists]
RMeterInterval:  60.  # update interval in sec.
RMeterRate:  0.7  # max rate in Hz
RMeterTitle: 'gamma rate history (s)'
histograms:
 - [0., 0.4, 50, 20., "noise Trg. Pulse (V)", 0]
  # min max Nbins ymax    title              lin/log
 - [0., 0.8, 50, 15., "valid Trg. Pulse (V)", 0]
# - [0., 15.,  45, 7.5, "Tau (µs)", 1]
# - [0., 0.8, 50, 15., "Pulse Height (V)", 0]

doublePulse: false # switch to control double-pulse search



