# file PSconfig.yaml
# ------------------   
# PicoScope configuration for two channles (~150ns pulses, <300mV)

PSmodel: '2000a'                  # model type (2000a is default, for PS 220xB and 240xB)

# Channel configuration  
picoChannels: [A, B]              # active channels
## picoChannels: [A, B, C]        # for 4-channel scope
ChanModes:     [AC, AC, AC]       # AC or DC coupling
ChanRanges: [0.2, 0.2, 0.2]       # range 
ChanOffsets: [0.14, 0.16, 0.15]   # offset (not for model 2204x)
ChanColors: [darkblue, sienna, indigo]  # opional: colors for graphical display

## Trigger configuration
trgChan: A
trgThr: -40.E-3
trgTyp: Falling
pretrig: 0.05                     # % of samples stored before trigger (not for model 2204x)

## data acquition 
Nsamples: 4000                    # number of samplings per trigger
sampleTime: 16.E-6                # total sampling time; time distance between two sampling
#     in seconds, scientific      #  is nearest valid setting given by sampleTime/Nsamples
#     format with . and
