# example of a configuration file for PicoScope 2000B Series
#    connected to a GDK101 gamma counter

PSmodel: 2000a      # model type (default 2000a)

picoChannels:      [A]
## picoChannels:     [A]
ChanRanges:        [0.5]
ChanOffsets:       [-0.4]

sampleTime:   2.E-3    # scientific format with '.' and signed exponent 
Nsamples:     800

trgChan:    A
trgThr:     70.E-3
trgTyp:     Rising
trgTO:      90000 # timeout
pretrig:    0.05

