# example of a configuration file for PicoScope 2000 Series
#    connected to a PM tube of Kamiokanne version by Phywe

PSmodel: '2000a'      # model type (default 2000a)

picoChannels:      [A]
ChanRanges:        [0.05]
ChanOffsets:       [0.04]

sampleTime:   16.E-6    # scientific format with '.' and signed exponent 
Nsamples:     4000

trgChan:    A
trgThr:     -5.E-3
trgTyp:     Falling
pretrig:    0.05

